final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.5,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Nike Running Shoes',
    'price': 30.5,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '2',
    'title': 'Nike Jordans',
    'price': 55.5,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '3',
    'title': 'Air Jordans',
    'price': 50.75,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10, 11],
  },
  {
    'id': '4',
    'title': 'Bata Leather Boots',
    'price': 60.25,
    'imageUrl': 'assets/images/shoes_5.png',
    'company': 'Bata',
    'sizes': [8, 9, 10, 11, 12],
  },
  {
    'id': '5',
    'title': 'Bata Boots',
    'price': 45.5,
    'imageUrl': 'assets/images/shoes_6.png',
    'company': 'Bata',
    'sizes': [7, 8, 9, 10, 11],
  },
  {
    'id': '6',
    'title': 'Puma High-Top Sneakers',
    'price': 49.99,
    'imageUrl': 'assets/images/shoes_7.png',
    'company': 'Puma',
    'sizes': [7, 8, 9, 10, 11],
  },
  {
    'id': '7',
    'title': 'Addidas Yeezy',
    'price': 65.5,
    'imageUrl': 'assets/images/shoes_8.png',
    'company': 'Addidas',
    'sizes': [7, 8, 9, 10, 11],
  },
  {
    'id': '8',
    'title': 'Puma Unisex Shoes',
    'price': 49.9,
    'imageUrl': 'assets/images/shoes_9.png',
    'company': 'Puma',
    'sizes': [6, 7, 8, 9, 10, 11],
  },
  {
    'id': '9',
    'title': 'Addidas women\'s shoes',
    'price': 45.5,
    'imageUrl': 'assets/images/shoes_10.png',
    'company': 'Addidas',
    'sizes': [6, 7, 8, 9, 10],
  },
];